server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/javacommunitysite?autoReconnection=true;serverTimezone=UTC;
spring.datasource.username=newroot
spring.datasource.password=cheomuk201720^^

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

logging.level.org.hibernate.type.descriptor.sql=trace

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.profiles.include=oauth
spring.devtools.livereload.enabled=true
spring.main.allow-bean-definition-overriding=true

spring.thymeleaf.cache=false
